### ISSUE TITLE
Manual cleaning removed but pesky dawnguard.esm reported not clean

### ISSUE THREAD

**Issue by ghost** [AngryAndConflict/skyrim-utils#3]
Loot reports its still not clean, i tried to clean it manually but you disabled that function,
so either Loot reports something wrong or sseedit does not clean this file.
Before you ask yes i tried clean it 3 times but i can do it till i die nothing changes.

Loots message : 
Dawnguard.esm  87E3D764
C.Location, C.Regions, Delev, Invent, Relev
This plugin contains wild edits beyond ITM and UDR records and deleted navmeshes and may require additional manual cleaning to not interfere with other mods. Dawnguard.esm Wild Edits Cleaning Guide

**Comment by MattsAttack1** [comment]
I have the same problem. LOOT gives a link but it is outdated. Therefore, I have no way to Manually Clean this. Is LOOT this bad, that it will give me such a message that obviously demands my attention, yet gives me no way to fix it? This is not "immersive" :)

**Comment by AngryAndConflict** [comment]
I'm afraid it has nothing to do with my script... or maybe SSEEdit was updated, I was not active TES gamer for quite a while... I'm sorry.
